{"uuid": "bd09fbf2-5a46-4331-a52a-f94de077c915", "children": ["3bcd162e-7f8f-48e8-ac6b-59c36fb0040d"], "befores": [{"name": "logged_in_page", "status": "failed", "statusDetails": {"message": "Failed: Login failed: Unknown error (possible timeout)\n", "trace": "  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\conftest.py\", line 77, in logged_in_page\n    pytest.fail(f\"Login failed: {error}\")\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1747816426788, "stop": 1747816444681}], "start": 1747816426788, "stop": 1747816444808}