{"uuid": "448b882a-7952-4bb4-86c9-bb36eb533801", "children": ["3b3f38dc-7fc6-42f6-9c20-a6ed0fbc27c0"], "befores": [{"name": "logged_in_page", "status": "failed", "statusDetails": {"message": "Failed: Login failed: Unknown error (possible timeout)\n", "trace": "  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\conftest.py\", line 78, in logged_in_page\n    pytest.fail(f\"Login failed: {error}\")\n  File \"C:\\Users\\lenovo\\Desktop\\nawat-automation-master\\venv\\lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1747214940411, "stop": 1747214966708}], "start": 1747214940411, "stop": 1747214966883}