{"name": "test_invalid_login[fr]", "status": "broken", "statusDetails": {"message": "NameError: name 'json' is not defined", "trace": "@pytest.fixture(scope=\"session\")\n    def config():\n        try:\n            with open('data/config.json', 'r', encoding='utf-8') as f:\n>               config_data = json.load(f)\nE               NameError: name 'json' is not defined\n\nconftest.py:99: NameError"}, "description": "Test login with invalid credentials", "attachments": [{"name": "test_invalid_login[fr]_setup_error", "source": "083e0300-7497-4497-a71d-cd8c5d6bd77e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "language_code", "value": "'fr'"}], "start": 1747139666336, "stop": 1747139666336, "uuid": "3c1cc5ff-30e4-43e0-a6a8-0145f289a8f0", "historyId": "d1c95e370e990bfe6c0644a1d243bbd4", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-LKP4IQM"}, {"name": "thread", "value": "16604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}