{"name": "test_invalid_login[en]", "status": "broken", "statusDetails": {"message": "NameError: name 'json' is not defined", "trace": "@pytest.fixture(scope=\"session\")\n    def config():\n        try:\n            with open('data/config.json', 'r', encoding='utf-8') as f:\n>               config_data = json.load(f)\nE               NameError: name 'json' is not defined\n\nconftest.py:99: NameError"}, "description": "Test login with invalid credentials", "attachments": [{"name": "test_invalid_login[en]_setup_error", "source": "bf5083f3-8522-4baf-8f55-93515c1326c1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "language_code", "value": "'en'"}], "start": 1747139666287, "stop": 1747139666287, "uuid": "47831987-0e95-4bc7-8b64-e9324e3a52a5", "historyId": "c8e47996fb07b28a09d44118231f0c35", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-LKP4IQM"}, {"name": "thread", "value": "16604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}