{"name": "test_invalid_login[ar]", "status": "broken", "statusDetails": {"message": "NameError: name 'json' is not defined", "trace": "@pytest.fixture(scope=\"session\")\n    def config():\n        try:\n            with open('data/config.json', 'r', encoding='utf-8') as f:\n>               config_data = json.load(f)\nE               NameError: name 'json' is not defined\n\nconftest.py:99: NameError"}, "description": "Test login with invalid credentials", "attachments": [{"name": "test_invalid_login[ar]_setup_error", "source": "3170fb70-a807-4fdd-bc90-aaa70ace19d5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "language_code", "value": "'ar'"}], "start": 1747139666373, "stop": 1747139666373, "uuid": "254211be-042c-46b7-8405-3475231f9df4", "historyId": "96ecfd8a220be0320d87eddcb8b88d73", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-LKP4IQM"}, {"name": "thread", "value": "16604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}